config/routes.rb
Rails.application.routes.draw do

  resources :requests
  resources :requests
  root 'main#index'
  get 'mail' => 'main#mail'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'employee_requests' => 'main#employee_requests'

end

app/models/request.rb
class Request < ActiveRecord::Base
	# Status and absence Type Enums
  	enum status:       { requested: 'status_requested',
                       approved: 'status_approved',
                       denied: 'status_denied' }

  	enum absence_type: { full: 'absence_full',
                       sickness: 'absence_sickness',
                       partial: 'absence_partial' }

  attr_accessor :partial_starting, :starting_time, :end_time

  belongs_to :user
  belongs_to :approver, class_name: 'User'

  validates :user_id, :approver,
            :absence_type,
            presence: true

  with_options unless: :partial? do |np|

    # Start date must start after today
    np.validates_date :starting_date, on: :create, on_or_after: :today
    # End date must be after start date
    np.validates_date :end_date, on: :create, after: :starting_date

    np.validates      :no_days,
                      numericality: { only_integer: true,
                                      greater_than_or_equal_to: 1 }
  end

  with_options if: :partial?, on: :create do |p|
    p.validates_date :partial_starting, on_or_after: :today
    p.validates_time :starting_time
    p.validates_time :end_time, after: :starting_time
  end

  after_initialize :set_default_values

  def set_default_values
    self.absence_type ||= Request.absence_types[:full]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests
  has_many :assigned_requests,class_name: "Request",foreign_key: 'approver_id'
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #User SessionHelper to manage user session
  include SessionsHelper

  #Use AuthorizationHelper to check if a user need to log in
  include AuthorizationHelper
end

app/controllers/main_controller.rb
class MainController < ApplicationController
   # User must be authenticated
  before_action :authorized_user
  # Confirm user is authorized as manager to view incoming
  before_action :is_manager, only: [:incoming]

  # View own requests
  def index
    @requests = logged_user.requests.order(updated_at: :desc)
  end

  # View incoming requests
  def employee_requests
    @requests = logged_user.assigned_requests.order(created_at: :desc)
  end

  def is_manager
    redirect_to(root_url) unless logged_user.manager?
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
   # User must be authenticated
  before_action :authorized_user
  # Check if a user is manager so he can review requests
  before_action :is_assigned, only: [:show, :update]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    @request.user = logged_user

    @request.status = Request.statuses[:requested]

    if @request.partial? && @request.valid?
      begin
        time = Time.parse(@request.starting_time)
        @request.starting = Time.parse(@request.partial_starting)
                                .change(hour: time.hour,
                                        minute: time.min)
        time = Time.parse(@request.end_time)
        @request.end_date = @request.starting_date
                                  .change(hour: time.hour,
                                          minute: time.min)
      rescue
      end
    end

    if @request.save

      Mailer.mail_request(@request).deliver_later
      flash[:success] = 'Your absence request has been submitted successfully!'
      redirect_to root_path
    else
      render :new
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    if params['approved']
      @request.status = Request.statuses[:approved]
    elsif params['denied']
      @request.status = Request.statuses[:denied]
    end

    if @request.update_attributes(update_params)
      Mailer.mail_status(@request).deliver_later
      redirect_to employee_requests_path
    else
      render 'show'
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:description, :starting_date, :starting_time, :end_date, :end_time, :absence_type, :comment, :no_days, :approver_id)
    end

    def is_assigned
      request = Request.find(params[:id])
      redirect_to(root_url) unless request.approver == logged_user
    end

    def update_params
      params.require(:request).permit(:comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	redirect_to :root if logged_in?
  end

  # Performs authentication
  def create
  	user = User.find_by(email: params[:email].downcase)

  	if user && user.authenticate(params[:password])
  		log_in user
  		redirect_to :root
  	else
  		flash.now[:error] = 'Invalid email/password combination'
      	render 'new'
    end
  end

  def destroy
  	log_out if logged_in?
    redirect_to login_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
    	{ success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  	end

  	def flash_messages(opts = {})
    	flash.each do |msg_type, message|
      		concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
            	concat content_tag(:button, 'x'.html_safe, class: "close", data: { dismiss: 'alert' })
              	concat message 
           end)
    	end
    	nil
  	end
end

app/helpers/authorization_helper.rb
module AuthorizationHelper
  # Forces a non authorized user to login
  def authorized_user
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #Registers a logged in user in the session
  def log_in(user)
    session[:user_id] = user.id
  end

  #Returns the currently logged in user
  def logged_user
    @logged_user ||= User.find_by(id: session[:user_id])
  end

  #Checks if user is logged in
  def logged_in?
    !logged_user.nil?
  end

  #Logs out a user
  def log_out
   session.delete(:user_id)
   @current_user = nil
 end

 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ARVSM - Absence Request and Vacation Schedule Management System<</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'myStyle' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<% if logged_in? %>
			<nav class="navbar navbar-default">
	  			<div class="container-fluid">
	    			<div class="navbar-header">
	      				<a class="navbar-brand" href="#">AVRSM</a>
	    			</div>
	    			<ul class="nav navbar-nav">
	      				<li> <%= link_to "My Requests", root_path %></li>
	      				<li> <%= link_to "Employee Requests", employee_requests_path if logged_user.manager? %></li>
	    			</ul>
	    			<div class="nav navbar-nav navbar-right">
	    				<ul class="nav navbar-nav">
	    					<li><a><%=logged_user.name %></a></li>
               				<li><%= link_to "Log out", logout_path, method: :delete,class:'ui item' %></li>
               			</ul>
           			</div>
	  			</div>
			</nav>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/main/employee_requests.html.erb
<ol class="breadcrumb">
  <li class="active">Control Panel</li>
</ol>

<div class="panel panel-default">
	<div class="row-fluid">
		<h3>Employee Requests</h3>
	</div>

	<br class="rwd-break">

	<div class="container-fluid">

		<table class="table table-bordered table-hover">
	    	<thead>
	      		<tr>
	        		<th>Employee</th>
	        		<th>Type</th>
	        		<th>Start Date</th>
			        <th>End Date</th>
			        <th>Number of Days</th>
			        <th>Status</th>
			        <th>Action</th>
	      		</tr>
	    	</thead>
		    <tbody>
		    	 <%@requests.each do |request| %>
      				<tr>
      					<td><%= request.user.name %></td>
        				<td><%= t "request_absence_type.#{request.absence_type}" %> </td>
				        <td>
				          <% if request.partial? %>
				          <%= l request.starting_date.to_date, format: :long  %>
				          -
				          <%= l request.starting_date, format:  '%H:%M'  %>
				        <% else %>
				          <%= l request.starting_date.to_date, format: :long %>
				          <% end %>

				        </td>
				        <td>
				          <% if request.partial? %>
				          	<%= l request.end_date, format: '%H:%M'  %>
				          <% else %>
				          	<%= l request.end_date.to_date, format: :long %>
				          <% end %>
				        </td>
				        <td>
				          <% unless request.partial? %>
				          	<%=  request.no_days %>
				          <% end %>
				        </td>
        				<td>
          					<%= t "request_status.#{request.status}" %>
        				</td>
        				<td>
				          <div style="display:none"><%= request.comment %></div>
				          <% if request.requested? %>
				          <a href="<%= request_path(request) %>" class="ui tiny basic  button modal-trigger">
				            <i class="unhide icon"></i>
				            Decide
				          </a>
				          <% end %>
				        </td>
				     </tr>
				     
      			<% end %>
		    </tbody>
	  	</table>
	  </div>
</div>

app/views/main/index.html.erb
<ol class="breadcrumb">
  <li class="active">Control Panel</li>
</ol>

<div class="panel panel-default">
	<div class="row-fluid">
		<h3>My Requests</h3>
		<a href="/requests/new" class="btn btn-info" role="button">New Request</a>
	</div>

	<br class="rwd-break">

	<div class="container-fluid">

		<table class="table table-bordered table-hover">
	    	<thead>
	      		<tr>
	        		<th>Type</th>
	        		<th>Start Date</th>
	        		<th>End Date</th>
	        		<th>Number of Days</th>
	        		<th>Reporting Manager</th>
	        		<th>Status</th>
	        		<th>Comment</th>
	      		</tr>
	    	</thead>
		    <tbody>
		    	 <%@requests.each do |request| %>
      				<tr>
        				<td><%= t "request_absence_type.#{request.absence_type}" %> </td>
				        <td>
				          <% if request.partial? %>
				          <%= l request.starting_date.to_date, format: :long  %>
				          -
				          <%= l request.starting_date, format:  '%H:%M'  %>
				        <% else %>
				          <%= l request.starting_date.to_date, format: :long %>
				          <% end %>

				        </td>
				        <td>
				          <% if request.partial? %>
				          	<%= l request.end_date, format: '%H:%M'  %>
				          <% else %>
				          	<%= l request.end_date.to_date, format: :long %>
				          <% end %>
				        </td>
				        <td>
				          <% unless request.partial? %>
				          	<a><%=  request.no_days %></a>
				          <% end %>
				        </td>
        				<td><%= request.approver.name %></td>
        				<td>
          					<%= t "request_status.#{request.status}" %>
        				</td>
        				 <td>
				          <%= request.comment %></td>
				     </tr>
				     
      			<% end %>
		    </tbody>
	  	</table>
	  </div>
</div>

app/views/requests/_form.html.erb
<script type="text/javascript">
  $(function () {
    $('#request_starting_date').datetimepicker({timepicker: false, format: 'Y/m/d'});
    $('#request_end_date').datetimepicker({timepicker: false, format: 'Y/m/d'});
    $('#request_partial_starting').datetimepicker({timepicker: false, format: 'Y/m/d'});
    $('#request_starting_time').datetimepicker({timepicker: true, datepicker: false, format: 'H:i'});
    $('#request_end_time').datetimepicker({timepicker: true, datepicker: false, format: 'H:i'});

    $('input:radio').change(function () {
      if ($(this).val() == 'partial') {
        $(".full-absence").hide();
        $(".partial-absence").show();
      } else {
        $(".full-absence").show();
        $(".partial-absence").hide();
      }
    });

    $('input:radio').filter(':checked').change();
  });
</script>

<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <label>absence type: </label>
      <%= f.radio_button :absence_type, 'full'  %>
      <label>Full</label>
      <%= f.radio_button :absence_type, 'sickness'  %>
      <label>Sickness</label>
      <%= f.radio_button :absence_type, 'partial'  %>
      <label>Partial</label>
  </div>

  <div class="form-group full-absence">
      <label>Start Date: </label><br>
      <%= f.text_field :starting_date %><br>
      <label>End Date:</label><br>
      <%= f.text_field :end_date %><br>
      <label>Working Days</label><br>
      <%= f.text_field :no_days %>
  </div>

  <div class="form-group partial-absence">
      <label>Date: </label><br>
      <%= f.text_field :partial_starting %><br>
      <label>Starting Hour:</label><br>
      <%= f.text_field :starting_time %><br>
      <label>End Hour:</label><br>
      <%= f.text_field :end_time %>
  </div>

 <div class="form-group">
      <label>Assign to: </label><br>
      <%= f.select(:approver_id,
                   User.where(manager:true)
                       .where.not(id:logged_user.id)
                       .collect {|p| [ p.name, p.id ] },
                   {},{} )%>
</div>
<div class="form-group">
      <label>Description: </label><br>
      <%= f.text_field :description %>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Starting date</th>
      <th>End date</th>
      <th>Absence type</th>
      <th>Status</th>
      <th>Comment</th>
      <th>No days</th>
      <th>Approver</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.description %></td>
        <td><%= request.starting_date %></td>
        <td><%= request.end_date %></td>
        <td><%= request.absence_type %></td>
        <td><%= request.status %></td>
        <td><%= request.comment %></td>
        <td><%= request.no_days %></td>
        <td><%= request.approver_id %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Control Panel', root_path %></li>
  <li class="active">New Request</li>
</ol>


<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/requests/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Control Panel', employee_requests_path %></li>
  <li class="active">Approve Request</li>
</ol>

<p id="notice"><%= notice %></p>

<div class="form-group">
  <label>Employee Name:  </label><br> <%= @request.user.name %><br>

  <label>Occupation:</label><br> <%= @request.user.position %><br>

  <label>absence Type:</label><br> <%= @request.absence_type %><br>
</div>

<div class="form-group">
  <% if @request.partial? %>
    <label>Date</label>
    <%= l @request.starting_date.to_date, format: :long  %>  <div class="field">
    <label>Starting Hour</label>
    <%= l @request.starting_date, format:  '%H:%M'  %>
    <label>End Hour</label>
    <%= l @request.end_date, format:  '%H:%M'  %>

  <% else %>
    <label>Starting Date: </label>
    <%= l @request.starting_date.to_date, format: :long  %>
    <label>End Date: </label>
    <%= l @request.end_date.to_date, format: :long  %>
    <label>Working Days: </label>
    <%= @request.no_days %>

  <% end %>

</div>

<div class="form-group">
  <label>Description:  </label><br> <%= @request.description %>
</div>

<%= form_for(@request) do |f| %>
  <div class="form-group">
    <label>Leave comment: </label><br>
    <%= f.text_area :comment, rows:5, cols:80 %>
  </div>

  <div class="span2 col-md-2 ">
    <p><%= f.submit 'Approve' , class: 'btn-success btn-block', name: 'approved' %></p>
    <p><%= f.submit 'Deny' , class: 'btn-danger btn-block',name:'denied' %></p>
  </div>
<% end %>